apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
    replicas: 3
    selector:
      matchLabels:
        app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
          - name: web
            image: ramkrishnatest/simplilearn-0107
            ports:
              - containerPort: 80
